services:
  db:
    image: postgres:16-alpine
    container_name: pm-postgres
    environment:
      POSTGRES_USER: passmanager
      POSTGRES_PASSWORD: passmanager
      POSTGRES_DB: passmanager
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U passmanager"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pm-api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app:rw
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --proxy-headers"
